#' Generate Binary Response Variable
#'
#' This function generates a binary response variable \(y\) for a given dataset and
#' a vector of coefficients. The function calculates the log-odds for each observation,
#' applies the inverse logit function to obtain probabilities, and then generates a
#' binary response using a Bernoulli distribution based on these probabilities.
#'
#' @param df Dataframe or matrix. The dataset of predictor variables for which the response variable is generated.
#' @param beta Numeric vector. The vector of coefficients corresponding to the predictor variables.
#'
#' @return A binary response vector generated from a Bernoulli distribution.
#'
#' @details
#' The function first converts the input dataset and coefficient vector into matrices. It then
#' computes the log-odds by multiplying the predictor matrix by the coefficient matrix. The log-odds
#' are transformed into probabilities using the inverse logit function. Finally, a binary response is
#' generated by drawing from a Bernoulli distribution with the computed probabilities.
#'
#' @examples
#' # Example usage
#' df <- matrix(rnorm(100), nrow = 10, ncol = 10)
#' beta <- rnorm(10)
#' y <- generate_y(df, beta)
#'
#' @export

generate_y <- function(df,
                       beta){

  #make the data into a matrix
  X <- as.matrix(df)
  b <- as.matrix(beta)

  #mean response
  log_odds <- X %*% b

  #pass through inv-logit function
  pr <- 1 / (1 + exp(-log_odds))

  #bernoulli response variable
  y <- rbinom(nrow(df), 1, pr)

  #return response
  y

}
